=head1 NAME

Karma - Changelog

=for html <body bgcolor="#3399cc">

=head1 DESCRIPTION

I've tried to keep track of version by version changes, and you'll find
most of them here.

=head1 Prerelease

=head2 07.15.99

=over 4

=item
o karmaclientd runs as daemon

=item
o cleaned up some globals

=back

=head2 09.02.99

=over 4

=item
o finished web graphics

=back

=head2 09.03.99

=over 4

=item
o finished installation, configuraiton, quickstart guides

=item
o finished download website

=back

=head1 Version 0.5.0

=head2 09.04.99

=over 4

=item
o First release

=back

=head1 Version 0.7.0

=head2 09.06.99

=over 4

=item
o fixed so logging messages are not buffered until program quits

=back

=head2 09.09.99

=over 4

=item
o added mail notification routine (Thanks Dennis)

=item
o added signal handling (Thanks Mike)

=item
o added karmactl routine

=item
o added signal handlers for:

=over 4

=item
- HUP reread config file

=item
- USR1 return status

=item
- TERM exit gracefully

=back

=back

=head2 09.10.99

=over 4

=item
o revamped karma.conf

=over 4

=item
- added preference groups 

=item
- added warning and alert notification

=item
- added settings for blinking/noblinking icons

=back

=back

=head2 09.11.99

=over 4

=item
o got email notification working fairly well

=back

=head2 09.12.99

=over 4

=item
o setup karma-user, karma-dev, karma-announce email lists

=item
o setup factory defaults (valid defauls if a service isn't specified
  in karma.conf file)

=item
o if no karma.conf file but DBI_DSN, DBI_USER, DBI_PASS are set,
  uses those, and monitors that database

=item
o replaced standard perl open and filehandles with new IO::File calls

=back

=head2 09.20.99

=over 4

=item
o got readConfig working on HUP signal

=item
o using new preference hierarchy (factory, default, and user defined)

=item
o services specified, but with no values use factory defaults

=back

=head2 09.21.99

=over 4

=item
o karmactl getting status via named pipe

=item
o karmad creates pid file while running

=item
o karmactl now looks for pid file to control running karmad

=back

=head2 09.23.99

=over 4

=item
o checking for Mail::Send package before using it

=item
o exit with useful message if DBI not installed

=item
o exit with useful message if DBD::Oracle not installed

=item
o reread config file from karmactl working

=item
o karmactl cleanup dynamic files option

=item
o karmactl stop option working

=item
o karmactl status has last updated times, service status

=item
o KARMA_HOME default location for karma.pid, karmafifo

=item
o added logfile to karmagentd

=item
o better error logging to karmagentd

=back

=head2 09.29.99

=over 4

=item
o fixed problem with notification and intervals

=item
o fixed problem time truncation problem (intervals)

=item
o karmagentd cleans up & exits with TERM signal 

=back

=head2 09.29.99

=over 4

=item
o released

=back

=head1 Version 0.9.0

=head2 11.04.99

=over 4

=item
o fixed time updating problems

=item
o handle autoextend datafiles (set to no_status)

=back

=head2 11.14.99

=over 4

=item
o karmactl status returns correct start time

=back

=head2 11.15.99

=over 4

=item
o added deftran queue monitoring

=item
o added deftran error monitoring

=back

=head2 11.17.99

=over 4

=item
o got repqueue, reperror working, info pages etc

=item
o finally got use strict working

=item
o created karma.pm for common code

=back

=head2 11.22.99

=over 4

=item
o added preference group sections on generated karma monitor page

=item
o on/off flag in config file

=back

=head2 11.25.99

=over 4

=item
o when multiple pref groups have different services enabled,
  unmonitored services get "-" in table

=item
o karmactl -f forces a refresh of all monitored services against
  all monitored databases

=item
o cleaned up pref_groups datastructures

=item
o bkgd karmad, karmagentd automatically with fork ()

=back

=head2 11.27.99

=over 4

=item
o fixed services updating after db shutdown

=item
o moved full/short option to email_notify config

=item
o cleaned up notification

=item
o created basic config file

=back

=head2 11.29.99

=over 4

=item
o added help pages for repqueue, reperror

=item
o created prefgroups config file

=item
o repqueue, reperror help files

=back

=head1 Version 0.9.1

=head2 11.30.99

=over 4

=item
o credits.html, bugs.html docs

=back

=head2 12.02.99

=over 4

=item
o debugging with -d option

=item
o finds KARMA_HOME even after daemonize moves home dir to "/"

=item
o if KARMA_HOME directory can't be found, a message is logged

=back

=head1 Version 0.9.2

=head2 12.08.99

=over 4

=item
o various Win32 fixes

=item
o calling Win32::IsWin95, Win32::IsWinNT

=item
o signal handling unix only

=item
o daemonize which uses fork () only called on unix

=item
o backgrounding job on Win32 (from karmactl) with system
  ("start perl karmad -opts");

=item
o handling delimiter '/' on unix, '\\' on Win32

=back

=head1 Version 0.9.3

=head2 12.09.99

=over 4

=item
o cleaned up file/directory name setting code

=back

=head2 12.11.99

=over 4

=item
o converted all html and text documents to pod including
  credits, todo, changelog, bugs, config, contribute,
  futuredev, install, quickstart, readme, release, security,
  license, and services

=item
o created a script to generate html and text docs in the
  appropriate directories, MAJOR LABOR-SAVER


=back

=head2 12.12.99

=over 4

=item
o fixed up color contrast problems, using light-blue background, 
  black text

=item
o if no valid tnsnames are found, karma exits with message to logfile

=item
o fixed a major bug which was leaving the db handle screwed up after
  the fork in daemonize... moved daemonize to earlier place in code
  and also check dbh more often with ping, cleanup, and reconnect if
  necessary.  This forced me to add lots of checking, for valid $sth
  statement handles, to add $sth->finish calls, and sprinkled 
  debugMessage calls throughout the code.

=item
o fixed bug when no karma.conf file found, and karma uses DBI_USER,
  DBI_PASS, DBI_DSN...   

=back

=head1 Version 0.9.4

=head2 12.18.99

=over 4

=item
o added Makefile.PL, tested

=item
o info column titles moved to $main::titles at top

=item
o reviewed factory defaults

=item
o a tbsp with an autoextend datafile is always green

=item
o fixed bug with min_wakeup time (refresh interval)

=back

=head1 Version 0.9.5

=head2 1.3.00

=over 4

=item
o handling karmagentd win32 conditions

=item
o karmagentd logging messages

=item
o karmagentd checking for valid dbh, sth, reconnecting when necessary

=item
o karmagentd handling term, hup signals

=item
o karmagentd handles reset alertlog (reread from beginning) 

=item
o slowsql defaults to OK status

=back

=head2 1.19.00

=over 4

=item
o fixed problem where down DBs didn't respect unmonitored services

=item
o fixed misc "use of unitialized values" errors

=item
o karmagentd exits if can't find or open alert.log

=item
o cleaned up some "" where '' are better

=back

=head1 Version 0.9.6

=head2 3.16.00

=over 4

=item
o fixed big email notification bug

=item
o blinking icons config directive fixed, warn_blink=[false|no|0],
  alert_blink=[false|no|0], otherwise blinking icons are used

=item
o list of valid service names if debug_level = 2

=item
o karma returns error if ORACLE_HOME set to invalid directory

=item
o fragmentation checks only first 100 fragmented objs

=back

=head1 Version 0.9.7

=head2 6.23.00

=over 4

=item
o added support for configuring doc_root in karma.conf file

=item
o fixed bugs with config file from karmactl, karmad etc...

=item
o updated links page

=back

=head2 6.25.00

=over 4

=item
o added threshold warn and alert values to more info page

=item
o changed extents checking to >=

=item
o alertlog monitoring verifiable even when not running, or tables not created

=item
o password entered without echoing

=item
o various unitialized values errors fixed

=back

=head2 6.26.00

=over 4

=item
o docs explain services, how to tune, instead of karma config info

=back

=head1 Version 0.9.8

=head2 07.01.00

=over 4

=item
o fixed serious bug with karmagentd not starting, failed to read password
needed to chomp() password after ReadKey

=item
o karmagentd now checks for karma_agent, karma_os_stats,
  karma_alertlog_errors tables, exits if they don't exist

=item
o fixed -a option, sometimes working directory would get prepended to
  absolute path

=item
o fixed -t option, also specifying DBI_DSN environment variable supported
  now, and take precedence over command line options

=back

=head2 07.01.00

=over 4

=item
o fixed short emails so they use shortened service names

=item
o added configuration information in status output (karmactl -t)

=item 
o fixed uptime display in status output

=item
o tested for short and full email addresses, and notification worked fine

=item
o added -a option to karmactl, checks to see if karmad is running, 
  returns status via $? (0 ok, 1 not ok)

=item
o a bug surfaced where redolog errors generated 1000+ emails, however
there were a number of bugs I fixed in there, especially in relation
to accessing those data structures.  The bug has not resurfaced, and I
so far cannot reproduce it.
 
=back

=head1 Version 0.9.9

=head2 07.07.00

=over 4

=item
o readme.win32 document explaining win32 specific issues

=item
o about.html page updated for 1.0 release

=item
o added update interval (wakeup) to command line check status 

=item
o warning messages get emailed even while there are alert 
status messages

=item
o updated install document

=item
o karmagentd's default logfile is karmagent.log (was -)

=item
o updated readme file

=item
o karmagent.sav file changed to .karmagent.sav

=item
o fixed karmagentd bug, would fail on error messages starting with ORA-##:
because it would try to insert ##: as a number

=item
o been testing successfully with running version for 2+ days now, 
stability is quite good for both karmad and karmagentd

=back

=head1 Version 1.0.0

=cut



