=head1 NAME

Karma - Future Development

=for html <body bgcolor="#3399cc">

=head1 DESCRIPTION

There are already plans to expand on the functionality
present in Karma.  Here's a list of some of the things I'm
working on for a future release.

=head1 Details

=over 4

=item
o lynx browser support (no frames, no tables?)

=item
o configuration check tool (reads karma.conf file)

=item
o web interface

=item
o help page for adding new services

=item
o more services monitored

=over 4

=item
- hitratios dictcache, rowcache 

=item
- listener log monitor

=item
- trace/core file monitor

=item
- monitor sqlnet performance

=item
- archive dest directory

=item
- backup success

=item
- buffer busy waits

=item
- locks

=back

=item
o karma.conf

=over 4

=item
- specify frames/no frames/no tables support 

=item
- specify no html pages generated, text only

=item
- vertical/horizontal arrangement option

=back

=item
o whom to contact messages

=item
o look at adding graphing support http://www.munitions.com/~jra/cricket/

=item
o resetting services, once you've seen them, turn back to green
  (not sure if this fits into the non-CGI thinking so far...)

=item
o 7.x issues

=over 4

=item
- no autoextend column

=item
- first_time column in v$log is varchar2 (date in 8.x

=item
o info pages include warning, alert values

=back

=item
o NT issues

=over 4

=item
- signal handling

=item
- named pipe

=back

=item
o notify full includes url to info page this will require a new line
  in the config file like SERVER:http://www.something.com/karma onto
  which the rest can be appended

=item
o simplifying code by using views in "karma" schema
  (tremendous code simplification, maintenance easier, adding
   services easier, hides 7.x, 8.x issues)

=item
o Duncan's redolog monitoring ideas

=item
o reorganize code (OOP)

=item
o mySQL, other db modules

=item
o past 1 or 2 days worth of log data (with link and info page)

=item
o log statuses over time, use cricket for graphing

=item
o table only data which we can include in another html page

=back



