=head1 NAME

Karma - Release Notes

=for html <body bgcolor="#3399cc">

=head1 DESCRIPTION

This is hopefully the last release of karma before a stable 1.0
release.  I'm doing last minute tests to hopefully discover any
lingering bugs before I dub the software "stable".  Be sure to
check here:

=for html <a href="http://www.iheavy.com/karma">

karma homepage (http://www.iheavy.com/karma)

=for html </a>

for updates.

=cut
