=head1 NAME

Karma - TODO

=for html <body bgcolor="#3399cc">

=head1 DESCRIPTION

This document details the remaining tasks to finish for particular
versions of karma.  

=head1 2.0.0 - Complete Rewrite 

=over 4

=item
o object oriented, enabling non-Oracle db support

=item
o store sql in views, easily changed, less code in app

=item
o other new features

=back







