=head1 NAME

Karma - TODO

=for html <body bgcolor="#3399cc">

=head1 DESCRIPTION

This document details the remaining tasks to finish for particular
versions of karma.  

=head1 1.0.0

=over 4

=item
o remaining Win32 problems, check email notification

=item
o db down respects unmonitored services

=item
o decide on how to handle redo-log switching exception, a la D. Lawlie

=item
o alertlog monitoring should be verifiable even when no errors found

=item
o karmagentd error message if running as non-oracle user

=back


